spring:
  datasource:
    url: jdbc:mysql://localhost:3306/flywaytestdb?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: testuser
    password: testpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc.batch_size: 100
        default_batch_fetch_size: 100
        format_sql: true
        use_sql_comments: true
    show-sql: true
